### ISSUE TITLE
working unblocker pls

### ISSUE THREAD

**Issue by pluh4life** [SparkTricks/SchoolBookmarks#4]

**Comment by SparkTricks** [comment]
What do you mean? Did you want a certain website unblocked?

**Comment by SparkTricks** [comment]
If you want that, I can’t do that. But if you are talking about the ad remover, what site is it happening on?

**Comment by SparkTricks** [comment]
It seems you haven't responded in a few months. I will close this issue, but you can open a new one with more detail.
